### ISSUE TITLE
Espacio entre celdas en tabla Administración de Servicios

### ISSUE THREAD

**Issue by jforni** [antich98/rollingVetFront#55]
En la colmna de los botones, hay celdas que dejan un espacio con las celdas de abajo. 
![Espacio entre celdas](https://github.com/antich98/rollingVetFront/assets/6042663/619538ac-39b7-4a3f-a804-977a0644e846)

**Comment by nicoleonard** [comment]
se hacia ese espacio cuando el texto del medio hacia crecer la fila, le cambie para q el texto no ocupe mas renglones
