### ISSUE TITLE
Espacio entre botones en Administración de servicios

### ISSUE THREAD

**Issue by jforni** [antich98/rollingVetFront#64]
Los botones de editar y borrar quedan muy pegados, lo ideal sería darles un poco de espacio
![Texto en botones-2](https://github.com/antich98/rollingVetFront/assets/6042663/ed2a8b3e-9e01-4e14-acc8-d434fe2015c1)

**Comment by nicoleonard** [comment]
los puse lado a lado y con un pequeño margen asi sean consistentes con las otras tablas
